package com.university.social.SocialUniProject.enums;

public enum NotificationType {
    COMMENT,
    NEW_POST,
    REACTION,
    FRIEND_REQUEST,



    GROUP_INVITE,
    GROUP_JOIN,
    GROUP_LEAVE,
    GROUP_JOIN_REQUEST,
    GROUP_CREATED,
    GROUP_JOIN_APPROVED,
    GROUP_JOIN_REJECTED,
    GROUP_JOINED,
    GROUP_LEFT,
    GROUP_DELETED,
    GROUP_VISIBILITY_CHANGED,
    GROUP_OWNERSHIP_TRANSFERRED,
    GROUP_REMOVED,
    GROUP_ADDED,
    GROUP_UPDATED,


    // Post-related
    POST_CREATED,
    POST_UPDATED,
    POST_DELETED,
    POST_UPDATED_BY_ADMIN,
    POST_DELETED_BY_ADMIN,

    // Event-related
    EVENT_CREATED,
    EVENT_UPDATED,
    EVENT_DELETED,
    EVENT_RSVP,
    EVENT_INVITATION
}