package com.university.social.SocialUniProject.enums;

public enum NotificationType {
    // User-related
    USER_REGISTERED,
    USER_UPDATED,
    USER_DELETED,
    USER_BLOCKED,
    USER_UNBLOCKED,
    USER_REPORTED,
    USER_VERIFIED,
    USER_ROLE_CHANGED,

    // Post-related
    POST_CREATED,
    POST_UPDATED,
    POST_DELETED,
    POST_UPDATED_BY_ADMIN,
    POST_DELETED_BY_ADMIN,
    POST_REPORTED,
    POST_APPROVED,
    POST_REJECTED,
    POST_ARCHIVED,
    POST_UNARCHIVED,
    POST_PINNED,
    POST_UNPINNED,
    POST_REACTION,

    // Comment-related
    COMMENT_CREATED,
    COMMENT_UPDATED,
    COMMENT_DELETED,
    COMMENT_REPORTED,
    COMMENT_APPROVED,
    COMMENT_REJECTED,
    COMMENT_HIDDEN,
    COMMENT_UNHIDDEN,
    COMMENT_LIKED,
    COMMENT_REPLIED,
    COMMENT_REACTION,

    // Event-related
    EVENT_CREATED,
    EVENT_UPDATED,
    EVENT_DELETED,
    EVENT_RSVP,
    EVENT_INVITATION,
    EVENT_CANCELLED,
    EVENT_POSTPONED,
    EVENT_REPORTED,
    EVENT_APPROVED,
    EVENT_REJECTED,
    EVENT_STARTING_SOON,
    EVENT_COMPLETED,
    EVENT_REMINDER,

    // Group-related
    GROUP_CREATED,
    GROUP_UPDATED,
    GROUP_DELETED,
    GROUP_JOIN_REQUEST,
    GROUP_JOIN_APPROVED,
    GROUP_JOIN_REJECTED,
    GROUP_LEFT,
    GROUP_REMOVED,
    GROUP_ROLE_CHANGED,
    GROUP_SETTINGS_UPDATED,
    GROUP_REPORTED,
    GROUP_ARCHIVED,
    GROUP_UNARCHIVED,
    GROUP_MEMBER_LEFT,
    GROUP_MEMBER_REMOVED,
    GROUP_OWNERSHIP_TRANSFERRED,
    GROUP_MEMBER_ADDED,

    // System notifications
    SYSTEM_ANNOUNCEMENT,
    SYSTEM_UPDATE,
    SYSTEM_MAINTENANCE,
    SYSTEM_ERROR,
    SYSTEM_WARNING,
    SYSTEM_INFO,

    // Admin notifications
    ADMIN_ACTION_REQUIRED,
    ADMIN_REPORT_RECEIVED,
    ADMIN_USER_REPORTED,
    ADMIN_CONTENT_REPORTED,
    ADMIN_ACTION_COMPLETED,
    ADMIN_ACTION_FAILED,
    ADMIN_SYSTEM_ALERT,

    // General notifications
    REACTION
}